language: python
dist: trusty


matrix:
  include:
  - python: 2.6
  - python: 2.7
  - python: 3.3
  - python: 3.4
  - python: 3.5
    dist: xenial
  - python: 3.6
    dist: xenial
  - python: 3.7
    dist: xenial
  - python: pypy
  - python: pypy3
  allow_failures:
  - python: pypy
  - python: pypy3

install:
- gcc --version

script: python setup.py test
